// File generated by FlutterFire CLI.
// ignore_for_file: type=
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYvTqIItjdJPhzYZy3emnrQCVsArvHQYI',
    appId: '1:321178165720:web:e2c2fec1f5fa90154612ad',
    messagingSenderId: '321178165720',
    projectId: 'stayease-e6b48',
    authDomain: 'stayease-e6b48.firebaseapp.com',
    storageBucket: 'stayease-e6b48.firebasestorage.app',
    measurementId: 'G-ZSSFD99BLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVSSdB_UxTuX7iDp7G5zvBoUBWX19UVc',
    appId: '1:321178165720:android:4eb6fe121d8958634612ad',
    messagingSenderId: '321178165720',
    projectId: 'stayease-e6b48',
    storageBucket: 'stayease-e6b48.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjCiJWxxX5sGFovamPbrSA7UP4O3ohZn8',
    appId: '1:321178165720:ios:26ef7834484c4bb34612ad',
    messagingSenderId: '321178165720',
    projectId: 'stayease-e6b48',
    storageBucket: 'stayease-e6b48.firebasestorage.app',
    iosBundleId: 'com.stayease.stayease',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjCiJWxxX5sGFovamPbrSA7UP4O3ohZn8',
    appId: '1:321178165720:ios:26ef7834484c4bb34612ad',
    messagingSenderId: '321178165720',
    projectId: 'stayease-e6b48',
    storageBucket: 'stayease-e6b48.firebasestorage.app',
    iosBundleId: 'com.stayease.stayease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYvTqIItjdJPhzYZy3emnrQCVsArvHQYI',
    appId: '1:321178165720:web:2e47b38d5c3a73fa4612ad',
    messagingSenderId: '321178165720',
    projectId: 'stayease-e6b48',
    authDomain: 'stayease-e6b48.firebaseapp.com',
    storageBucket: 'stayease-e6b48.firebasestorage.app',
    measurementId: 'G-S7YD1MZ5B4',
  );
}
